# Generated by Django 5.2.1 on 2025-06-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='status',
            field=models.IntegerField(
                choices=[(0, 'Open'), (1, 'In Progress'), (3, 'Closed'), (4, 'Rejected')], default=0, max_length=20
            ),
        ),
    ]
