# Generated by Django 5.2.1 on 2025-06-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_alter_idea_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='status',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'Answered')], default=0, max_length=20),
        ),
    ]
