# Generated by Django 5.2.1 on 2025-09-05 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0003_alter_idea_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='answer_to',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='replies',
                to='ideas.comment',
            ),
        ),
    ]
