# Generated by Django 5.2.1 on 2025-09-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0004_comment_answer_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='signal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='idea',
            name='signal',
            field=models.BooleanField(default=False),
        ),
    ]
