# Generated by Django 5.2.1 on 2025-10-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0005_comment_signal_idea_signal'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.IntegerField(choices=[(0, 'Not published'), (1, 'Published'), (2, 'Answered')], default=0),
        ),
        migrations.AlterField(
            model_name='idea',
            name='status',
            field=models.IntegerField(
                choices=[(0, 'Not published'), (1, 'Published'), (2, 'Answered')], default=0, max_length=20
            ),
        ),
    ]
